# Generated by Django 6.0.3 on 2026-03-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(null=True, upload_to='complaints/'),
        ),
    ]
